### ISSUE TITLE
Delete/merge `newbranch` branch

### ISSUE THREAD

**Issue by notani** [MysteryVaibhav/vanGAN#2]
If this branch is no longer used, we might want to delete it.

**Comment by MysteryVaibhav** [comment]
I think now we can delete that branch

**Comment by notani** [comment]
Let's delete it

[![exp](http://tiqav.com/2s0.th.jpg)](http://tiqav.com/2s0)

**Comment by MysteryVaibhav** [comment]
Deleted !
