### ISSUE TITLE
Dropout after an activate function on a discriminator

### ISSUE THREAD

**Issue by notani** [MysteryVaibhav/vanGAN#3]
Currently we dropout values before linear transformation, but dropout should be **after** activation functions.

```python
    def forward(self, x):
        x = self.activation1(self.map1(self.drop1(x)))
        x = self.activation2(self.map2(self.drop2(x)))
        return F.sigmoid(self.map3(x)).view(-1)
```
https://github.com/MysteryVaibhav/vanGAN/blob/bbb831a1a99a66fb1b181ea293472a0a4200a015/src/model.py#L26

**Comment by MysteryVaibhav** [comment]
Fixed in the latest version
