### ISSUE TITLE
StopIteration error in training

### ISSUE THREAD

**Issue by notani** [MysteryVaibhav/vanGAN#5]
`next(g_iter)` may raise StopIteration error when there is no item.

https://github.com/MysteryVaibhav/vanGAN/blob/a8a74e0c80bcc16ce61be4727b55ca17e1822208/trainer.py#L77

Instead of using `next`, use

```python
        for d_real_data, d_gen_input in zip(it_data_loader, en_data_loader):
```
in
https://github.com/MysteryVaibhav/vanGAN/blob/a8a74e0c80bcc16ce61be4727b55ca17e1822208/trainer.py#L63

Note the number of iterations will be the same as `min(len(it_data_loader), len(en_data_loader))`

**Comment by MysteryVaibhav** [comment]
All iters were removed long time, fixed with the latest version
